### PR TITLE
37/add api documentation

### LINKED ISSUE #37: Add API documentation
Use [apiDoc](https://github.com/apidoc/apidoc).

[Example of apiDoc](http://apidocjs.com/example/)

### PR DESCRIPTION
**Pull request by AdamVig**
Closes #37.

Feel free to pull and open `./docs/apidoc/index.html` to see what it's like.

I included response examples for get, get all, and update endpoints and response properties for create and delete endpoints.

### CODE REVIEW

**Review by emroussel — CHANGES_REQUESTED** [review]
I love it! Would it be possible to document item filtering as well even though it's not in the controller?

Also, there is a section in the README about API documentation that can probably be reduced to simply mentioning to include the auth header with requests.

**Comment by AdamVig** [comment]
Yes! I will document filtering, I should have done that from the start.

I will simplify (or remove) the README documentation as well. ApiDoc has support for injecting a Markdown file, so I can use that to add general documentation about auth headers and HAL.

**Comment by AdamVig** [comment]
It looks like I already did document item filtering, and just forgot about it:
image
Should I improve this in some way, or do you think it's ok as-is?

**Comment by emroussel** [comment]
Oh I didn't see that. Hmm not sure how much control you have over that, but it would be great if there would be some header or description indicating that this is filtering. If not, it's fine though. We're the only ones who are going to use this api and I know where it is now.

~~Also, is there a way to see the header you just added with the html docs? I am just opening `index.html` right now, so I might be doing something wrong.~~ (I forgot to re generate the docs after pulling)

**Comment by AdamVig** [comment]
Added examples of using filters:
image

**Review by emroussel — APPROVED** [review]

**Pull request merged**
