### PR TITLE
3/set up and scaffold

### LINKED ISSUE #2: Set up continuous integration
Sign up for the below continuous integration services and integrate their badges with the `README`.

- [x] [Travis CI](https://travis-ci.org/)
- [x] [Coveralls](https://coveralls.io/)
- [x] [Code Climate](https://codeclimate.com/)
- [x] [GitMagic](https://gitmagic.io/)

### PR DESCRIPTION
**Pull request by AdamVig**
Closes #2 and #3.

### CODE REVIEW

**Comment by ghost** [comment]
Your pull request doesn't follow our guidelines. Please fix the following:

* Pull request description must include a screenshot [(?)](https://gitmagic.io/rules/#/pull-request/body-must-include-screenshot)
* Pull request description must include verification steps [(?)](https://gitmagic.io/rules/#/pull-request/body-must-include-verification-steps)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/7/75de7ac9-4433-46e3-83ff-643536c63c9c/52632fff-7603-43b1-a41a-8de3d9c1ddc6) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by AdamVig** [comment]
Ignore GitMagic, as it is currently using its default configuration instead of  the configuration introduced in this branch.

**Comment by AdamVig** [comment]
The poor code coverage in `db.js` will be addressed in #5.

**Comment by AdamVig** [comment]
Hopefully, Code Climate will run in future pull requests. I think it cannot run here because this branch introduces its configuration.

**Comment by ghost** [comment]
This pull request still violates some of our guidelines:

* Pull request description must include verification steps [(?)](https://gitmagic.io/rules/#/pull-request/body-must-include-verification-steps)

[Click here](https://app.gitmagic.io/AdamVig/stockpile-api/7/75de7ac9-4433-46e3-83ff-643536c63c9c/52632fff-7603-43b1-a41a-8de3d9c1ddc6) for details.

**Comment by AdamVig** [comment]
This was accidentally closed when I attempted to rebase changes and force push (in order to clean up my Git history). Note to self, never do that again. 😬  See #10 for the second attempt at this pull request.

**Pull request closed without merging**
